version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: carbon_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - carbon_network

  backend-node:
    build: ./backend-node
    container_name: carbon_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/carbon_footprint
      - ML_SERVICE_URL=http://ml-service:8001
      - JWT_SECRET=supersecret_carbon_key
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo
    networks:
      - carbon_network

  ml-service:
    build: ./ml-service
    container_name: carbon_ml
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongo:27017/carbon_footprint
    volumes:
      - ./ml-service/models:/app/models
    networks:
      - carbon_network

volumes:
  mongo_data:

networks:
  carbon_network:
    driver: bridge
